### ISSUE TITLE
Error while install libciffpp-data on Debian 12

### ISSUE THREAD

**Issue by Youngerkind** [PDB-REDO/libcifpp#70]
# Problem

`libcifpp-data` is required by many packages, but an error is frequently encountered. I think the reason is that the web address `https://ftp.wwpdb.org` has been deprecated ([announcement](https://www.wwpdb.org/news/news?year=2023#65562f0ad78e004e766a96c1)) and shall be replaced to `https://files.wwpdb.org`.

```bash
user@host:~$ sudo apt install libcifpp-data
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcifpp-data is already the newest version (5.0.7.1-1).
The following packages were automatically installed and are no longer required:
  linux-headers-6.1.0-34-amd64 linux-headers-6.1.0-34-common linux-image-6.1.0-34-amd64
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up libcifpp-data (5.0.7.1-1) ...
--2025-07-01 20:58:44--  https://mmcif.wwpdb.org/dictionaries/ascii/mmcif_pdbx_v50.dic.gz
Resolving mmcif.wwpdb.org (mmcif.wwpdb.org)... 132.249.213.156
Connecting to mmcif.wwpdb.org (mmcif.wwpdb.org)|132.249.213.156|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 594755 (581K) [application/x-gzip]
Saving to: ‘/var/cache/libcifpp/mmcif_pdbx.dic.gz’

/var/cache/libcifpp/mmcif_pdb 100%[=================================================>] 580.82K   542KB/s    in 1.1s

2025-07-01 20:58:46 (542 KB/s) - ‘/var/cache/libcifpp/mmcif_pdbx.dic.gz’ saved [594755/594755]

--2025-07-01 20:58:46--  https://ftp.wwpdb.org/pub/pdb/data/monomers/components.cif.gz
Resolving ftp.wwpdb.org (ftp.wwpdb.org)... failed: No address associated with hostname.
wget: unable to resolve host address ‘ftp.wwpdb.org’
dpkg: error processing package libcifpp-data (--configure):
 installed libcifpp-data package post-installation script subprocess returned error exit status 4
dpkg: dependency problems prevent configuration of libcifpp5:amd64:
 libcifpp5:amd64 depends on libcifpp-data; however:
  Package libcifpp-data is not configured yet.

dpkg: error processing package libcifpp5:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dssp:
 dssp depends on libcifpp5 (>= 5.0.7.1); however:
  Package libcifpp5:amd64 is not configured yet.

dpkg: error processing package dssp (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libcifpp-data
 libcifpp5:amd64
 dssp
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

# Temporary solution
For now, one can download the archive file from `https://files.wwpdb.org/pub/pdb/data/monomers/components.cif.gz` and put it at `/var/cache/libcifpp`

**Comment by mhekkel** [comment]
This was fixed in libcifpp some time ago already. It is not yet available in Debian though, that's because the Debian code is behind.

**Comment by Youngerkind** [comment]
Thank you for your reply. What should I do then? Write to Debian support or just wait?

**Comment by mhekkel** [comment]
The code in Debian in maintained by me as well, so you can report it there but I will have to handle it anyway ;-)

But then, the code in Debian already contains the new URL. So I wonder why you do still have the wrong one. You do have an up-to-date version of Debian 12 I understand?

**Comment by Youngerkind** [comment]
Oh, you have done a lot for the community!

I put some info below. Maybe that's because the problem is not fixed for `libcifpp-data 5.0.7.1-1`. 

`version of packages`
```
user@host:apt$ apt -s install libcifpp-data
NOTE: This is only a simulation!
      apt needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcifpp-data is already the newest version (5.0.7.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
Conf dssp (4.2.2-2 Debian:12.11/stable [amd64])
Conf libcifpp-data (5.0.7.1-1 Debian:12.11/stable [all])
Conf libcifpp5 (5.0.7.1-1 Debian:12.11/stable [amd64])
```

`version available in debian`
```
user@host:apt$ sudo apt search libcifpp-data
Sorting... Done
Full Text Search... Done
libcifpp-data/stable,now 5.0.7.1-1 all [installed]
  Data files for libcifpp
```

`version of the system`
```
user@host:~$ cat /proc/version
Linux version 6.1.0-33-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.133-1 (2025-04-10)
```
